language: rust
sudo: false
rust: nightly

matrix:
  fast_finish: true
  include:
    - name: "nvptx64-nvidia-cuda - cross compiled, build libcore only"
      env: TARGET=nvptx64-nvidia-cuda NORUN=1 NOSTD=1
    - name: "Documentation"
      install: true
      script: ci/dox.sh
    - name: "Automatic verification: x86 and x86_64"
      script: cargo test --manifest-path crates/stdsimd-verify/Cargo.toml
      install: true
    - name: "rustfmt"
      install: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check
      rust: stable
    - name: "clippy"
      install: true
      script: |
        if rustup component add clippy-preview ; then
            cargo clippy --all -- -D clippy::pedantic
        fi
    - name: "Shellcheck"
      install: true
      script:
        - shellcheck --version
        - shellcheck ci/*.sh

  allow_failures:
    # FIXME: https://github.com/rust-lang-nursery/stdsimd/issues/669
    - name: "powerpc-unknown-linux-gnu - no assert_instr"

install: travis_retry rustup target add $TARGET
script:
  - cargo generate-lockfile
  - ci/run-docker.sh $TARGET

notifications:
  email:
    on_success: never
env:
  global:
    secure: "jmh7FfVwtPYQN/xPrVYmX7ys70GvX9YsKYtDpp8UwtIihCr81KHi2P2a1/KZNvQN0gPO+nneKieCbNQSCEtxDG9plUoB+OhX8ov9g3ImTJbyt+oW35Vlqq9ftB+Hr/Wn42o4OSTYxRfy1gf9VMePBaJfdkuym3BB75K4s+k+akuVqJv+KAm3zz0wSqU4O/evj2EGz1ldMzqxpogrO2WJQkXyl4xaW/1E0y8IZfRy0bJPKALFUpTDp39ZiWvzjNdr8CXUW1DChJdFPNo7yswxyl/NL5e/meHqF2dzS5b0YyOhcCzlBm7eZoEwyHZWB73t7n5Tuo0uYpX/kBXPAvtDrljQjBNcpm9vJtg6sj3oG0bGAI8pJfNNpLdHLHO6CjmORGP/rzZLeRdEFVb8t7UIXG7l3NcoBpRNiwPFY4gpE5dgiRsKjNrtmNe3GahhsYwbPkc+QUeQFIDtYYRxdJVZj+KvU9jIEpRh5Zv8FZBfsfx0LcLEdtRBjJxFNGGO5NY8nP0OWNVyt4ckRbRMtVzcbcOdzcfUc74/wZYZj8SrfcbSqsfylMQbxLAHJCynvuFmoMf3udPqP3aPuO+4EjDYDIQ1kHwKK87lwqlXFHdhRepAmhRR//g3bDUxzXd96KJqbFU3MYZnn/jzIi0kl+jx3FxivT380cYLVjrD29aGc7M="
